### ISSUE TITLE
更新后还是空白，不显示地图。

### ISSUE THREAD

**Issue by nichwang88** [fineemb/lovelace-cn-map-card#1]
系统版本0.109.3，更新到V1.1，还是无法显示地图。
高德Key两种类型都试过。
PS：请问您这卡片应该用高德哪种Key，“Web服务”还是“Web端”？

**Comment by fineemb** [comment]
web端(jsAPI)

**Comment by nichwang88** [comment]
填不填Key都空白的，什么都显示不出来，只在加载的一开始显示高德地图，然后就一片空白。

**Comment by fineemb** [comment]
能F12看一下报错信息吗?

**Comment by nichwang88** [comment]
在哪里看，日志里我看不到卡片的报错信息

**Comment by fineemb** [comment]
你用的什么浏览器, 一般chrome系的浏览器,F12看开发面板里面的Console控制台

**Comment by nichwang88** [comment]
```
TypeError: Cannot set property 'onresize' of null                    cn-map-card.js:254
    at Object.watchSize (maps?callback=___onAPILoaded&v=2.0&key=056b395c12fad7b2ace47362075ab941&plugin=AMap.MoveAnimation:1)
    at Qs.Ga.cm (maps?callback=___onAPILoaded&v=2.0&key=056b395c12fad7b2ace47362075ab941&plugin=AMap.MoveAnimation:1)
    at Qs.Ga [as constructor] (maps?callback=___onAPILoaded&v=2.0&key=056b395c12fad7b2ace47362075ab941&plugin=AMap.MoveAnimation:1)
    at new Qs (maps?callback=___onAPILoaded&v=2.0&key=056b395c12fad7b2ace47362075ab941&plugin=AMap.MoveAnimation:1)
    at cn-map-card.js:152
```
```
TypeError: Cannot read property 'split' of undefined                cn-map-card.js:254
    at HTMLElement.<anonymous> (cn-map-card.js:164)
    at Array.forEach (<anonymous>)
    at cn-map-card.js:160
```

**Comment by fineemb** [comment]
能不能提供一下你标记点的friendly_name的数据, 谢谢!

**Comment by nichwang88** [comment]
标记点？你指的是Zone？有Home、Work、Nicholas Smart Home。你指的是这个吗？

**Comment by fineemb** [comment]
就是配置文件的entities里面的条目

**Comment by nichwang88** [comment]
```
        entities:
          - device_tracker.nicholas_iphone_xs_max
          - device_tracker.x3revise
```
应该不会是这个问题吧，我用官方的map能正常显示的嘛

**Comment by fineemb** [comment]
可能是我代码里面没过滤, 我这边已经修复,我只是想验证一下究竟是什么原因.
这两个设备的friendly_name属性是什么

**Comment by nichwang88** [comment]
一个是X3定位，一个是Nicholas iPhone XS MAX。
不过我刚刚尝试把任何其中一个删除，都无法正常显示地图。

**Comment by fineemb** [comment]
你这个配置不对吧?
        entities:
          - entity: device_tracker.nicholas_iphone_xs_max
          - entity: device_tracker.x3revise

**Comment by nichwang88** [comment]
没注意，你的地图跟官方配置不完全一样，加了“entity:”以后，能在中间显示设备圈，但是地图依然没有显示出来。

**Comment by nichwang88** [comment]
```
      - type: 'custom:cn-map-card'
        default_zoom: 9
        dark_mode: true
        hours_to_show: 72
        entities:
          - entity: device_tracker.nicholas_iphone_xs_max
          - entity: device_tracker.x3revise
        key: …………
```
这是我的全部配置，关于数字，''加了没加都一样不显示。我是yaml模式
